#This file is generated by ModuleSync, do not edit.

source ENV['GEM_SOURCE'] || "https://rubygems.org"

def location_from_env(env, default_location = [])
  if location = ENV[env]
    if location =~ /^((?:git|https?)[:@][^#]*)#(.*)/
      [{ :git => $1, :branch => $2, :require => false }]
    elsif location =~ /^file:\/\/(.*)/
      ['>= 0', { :path => File.expand_path($1), :require => false }]
    else
      [location, { :require => false }]
    end
  else
    default_location
  end
end

group :development, :test do
  gem 'metadata-json-lint'
  gem 'awesome_print'
  gem 'rubocop'
  gem 'rubocop-rspec'
  gem 'puppetlabs_spec_helper', '>= 1.2.1'
  gem 'puppet-lint', '~> 2'
end
group :doc do
  gem 'puppet-strings', '~> 1.0.0'
  gem 'redcarpet'
  gem 'rdoc'
end

gem 'facter', *location_from_env('FACTER_GEM_VERSION')
gem 'puppet', *location_from_env('PUPPET_GEM_VERSION')

if File.exists? "#{__FILE__}.local"
  eval(File.read("#{__FILE__}.local"), binding)
end
