# This file is generated by ModuleSync, do not edit.
require 'puppetlabs_spec_helper/module_spec_helper'

# put local configuration and setup into spec_helper_local
if File.exist?(File.expand_path(File.dirname(__FILE__), 'spec_helper_local.rb'))
  require_relative 'spec_helper_local'
end
